### ISSUE TITLE
Please ensure 4-wire transmission line symbols can be connected to

### ISSUE THREAD

**Issue by morciej** [Caneda/Caneda#12]
The 4-wire transmission line symbol terminals are on a 5 by 5 grid. These symbols cannot be connected to by wires, which are always placed on 10 by 10 grid. Please correct the definitions. Once I correct all of them, I can initiate a Pull Request.

**Comment by morciej** [comment]
Pull request ready.

**Comment by parejaobregon** [comment]
Hey @morciej, thanks for your commits and pull request. Also, nice catch, evidently I never used this component myself.

If you may, in the future, pull requests should be done to the develop branch instead of master, which is the one tracking the latest development.

In this case, I did reapply your changes in a new commit to the develop branch with a couple of modifications, so you don't need to do anything else on your side. Basically I moved not only the ports, but everything in the symbol (including the line drawings). I also moved all ports in the same direction. The basic idea being maintaining the proportions and geometry of the symbol.

Thanks again.

**Comment by parejaobregon** [comment]
Fixed in latest commit to develop branch (commit #[bd7fc19](https://github.com/Caneda/Caneda/commit/bd7fc195cbbe8e920aaf489f8adef1afe7e96bb4)).
