### ISSUE TITLE
Feature request: remember components fold state

### ISSUE THREAD

**Issue by morciej** [Caneda/Caneda#14]
Every time I open Caneda, all parts are in the unfolded state. The default state should be folded, so that we don't have to wade through scores of parts. It would be nice to also remember the fold state across sessions.

**Comment by parejaobregon** [comment]
This might be somewhat tricky. As far as I could find, there's no support currently in Qt to do this. The alternative is to save everything manually doing an iteration over all items and saving their status. This does not hold well when the included libraries is big (remember that the user can add lots of libraries in addition to the default ones, we even have a separate repo with hundreds of diode models).

Right now, even if the above was achievable, I'm not so sure the cost/benefit is worth it, having to store lots of info in the disk for this, with the added complexity in the code and settings reading.

Having said that, we still could strive for a better behaviour than what we have now. I'll try experimenting with having the **Components** sub-libraries (child items) collapsed by default.

**Comment by morciej** [comment]
I think that would be sufficient. I ended up ignoring it and just grabbing the scroll bar. The additional trouble is that components are not alphabetically sorted, so I can't find what I am looking for in those big transistor libraries.

**Comment by parejaobregon** [comment]
Fixed in latest commits.

Sorted items alphabetically, and set default expand behaviour to only show categories (really only 1 level). Additionally, the filter expands the categories when typing text so that items are discoverable, but when clearing the text, the expand will reset to default (collapsed).

Finally the quickinsert tool (shortcut key = i) will keep previous behaviour so that items are easily found (in this case I believe the use case is more geared towards keyboard filter interaction).

Please, check if the new behaviour is better. I might still tune it a little bit if you find odd behaviours before closing this issue.

Thanks.
