### ISSUE TITLE
Current controlled sources need freedom to point to components (not just voltage sources)

### ISSUE THREAD

**Issue by morciej** [Caneda/Caneda#24]
An issue I am running into while trying to set up an ideal transformer, by putting two sources back to back:

- a voltage source controlled by input voltage multiplied by transformer ratio, and
- a current source controlled by the output current multiplied by transformer ratio.

Because dependent current sources in Spice need to be pointed to a current in the circuit, I **need to be able to point them to any component**, such as a dependent source or a resistor.

Unfortunately, the way these components are set up is that they force a "**V**" as the first letter of the component pointed to. As a result, I get "VE1" not "EE1" and **an error**. **Only an independent voltage source can be used** as the measured current location successfully.

It seems necessary to drop the initial "V" from "V%property{Vnam}" in

- currentsourcescurrentcontrolled.xsym
- voltagesourcescurrentcontrolled.xsym

...although the user needs to remember to put in the complete name of the component, including the category ("EE1" not "E1".) I tried and it does work.

I am not putting in a pull request because maybe this is not the way to deal with the issue... so just a suggestion this time.

**Comment by parejaobregon** [comment]
As you point out, I don't think it's a good idea to remove the V prefix and let the user add the category by hand. First the user would need to know the category key, and there are too many categories to list in a simple description. Secondly, it's somewhat confusing trying to explain that in simple terms to a user that not necessarily knows about spice. And third it's too prone to errors since the user has complete freedom to put any text in there. I even knew what I had to do and had to struggle a little bit to get a working example to analyse this issue.

As I see it, we have currently two alternatives:

- Create a new component as suggested, in addition to the currently one available in the library. We could easily leave the one existing as is, and create an **advanced** one with a new property called "Category". Then the user might fill in the name without adding extra letters, and choose the category on the newly created parameter (separate from the controlling source name). The description of this parameter may give the user some hints, along the lines: "Use R for resistors, C for capacitors, etc".
- Achieve what you are proposing by using an **Ammeter** instead. This is already available in Caneda and you do not need to modify anything. Just put an **Ammeter** in series with whatever component you need as controlling current source, and then point the **Current/Voltage Source Current Controlled** to the **Ammeter** instead. I think this is relatively simple an has no drawback. See below as an example.

![imagen](https://github.com/user-attachments/assets/234f44af-3b8d-470a-a01d-f5c9d4af28aa)

What are your thoughts? If you still think the first option is better, let me know and I can create a couple of components for that.

Thanks.

**Comment by morciej** [comment]
Yes, the simple solution. And conveniently, these ammeters also have "V" auto-inserted into name. The reason I did not try this was that somehow in my Linux Mint packaged setup, "measurement" library was not in the list. I added it now. This also answers another question: "how do I plot a particular current or voltage".

Since you are just trying to set up a useful default, I would say leave setting up new components to "Examples" and user's initiative.

As a general thought, users can do a lot once they understand how things are arranged. Sometimes throwing in a "special" component without a thorough explanation just leaves it unused. As you said, this software is supposed to be beginner-friendly.

**Comment by parejaobregon** [comment]
As a side note, regarding:

> This also answers another question: "how do I plot a particular current or voltage".

You can place a **Port** anywhere in the schematic and assign it a name. That way you are setting a name for the selected net and it will get automatically added to the list of plots. But, giving you are naming a net, this method allows you only to plot voltages (hence I later on added the Ammeter and Differential Voltmeter components to improve flexibility).

If more than one connection is made to any **Port** (for example 2 wires are connected to it) the **Port** symbol mutates into a point to mimic a net connector.
