### ISSUE TITLE
New Logo for CANEDA 

### ISSUE THREAD

**Issue by sametceylan** [Caneda/Caneda#5]
Hello sir, I've tried contact you and i designed a new logo. I hope you like it.
![untitled-caneda](https://user-images.githubusercontent.com/34095452/37877192-df9814fe-305f-11e8-8379-815722b3a12a.jpg)
I can give you editable files.
![bandicam 2018-03-25 19-08-50-890](https://user-images.githubusercontent.com/34095452/37877250-c0f151b8-3060-11e8-8c1f-adf947600c89.png)
.png
![untitled-1](https://user-images.githubusercontent.com/34095452/37877284-5decf72e-3061-11e8-822d-7ec4dd96b44c.png)

**Comment by q2dg** [comment]
Well, it seems this project is pretty abandoned

**Comment by eMPee584** [comment]
This is a really good logo draft.. mmh.. :fast_forward:
somehow caneda's maintainer @parejaobregon has gone MIA?

**Comment by parejaobregon** [comment]
Sorry for taking so long to reply to this.

Thanks for your effort, but unluckily the proposed design doesn't hold right under all resolutions. Specially since we need to use the icon in small scenarios (e.g.):

![imagen](https://github.com/user-attachments/assets/692cc93b-190f-4fcc-9d61-7089e0cb0250)

Thanks again.
