### ISSUE TITLE
Library files/Can't find a forum for Caneda

### ISSUE THREAD

**Issue by ChrisOfBristol** [Caneda/Caneda#7]
I have a simple query about the Caneda component libraries which would easily be answered on a forum, so I would prefer to post it there rather than opening a bug report, but I can't find a forum.

I want to use a very standard component - an LED. I have loaded the Libraries-master from https://github.com/Caneda/Libraries and stopped and restarted Caneda, but can only see one diode on the list of available components - no LEDs.

**Comment by parejaobregon** [comment]
Sorry for the late reply. For the time being, there's no forum for Caneda, although it's a good idea for the future. Adding the procedure anyway, to keep as documentation, should anyone have similar issues.

In order to add new libraries, you need to add the downloaded folder via the "Settings -> Libraries -> Add Library..." option, and then restart the application.

More info on the "Component Libraries" section from the official documentation: http://docs.caneda.org/en/latest/libraries.html
